name: GitHub Actions 
run-name: ${{ github.actor }} GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      
        -name:23f1001029@ds.study.iitm.ac.in  
        run:echo" M.ANANTHAVALLI ${{ github.event_name }} "
        
    
      
