name: GitHub Actions 
run-name: ${{ github.actor }} GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      
        -run: echo "23f1001029@ds.study.iitm.ac.in ${{ github.event_name }}"      
        
        uses: actions/checkout@v4
      
        run: |
          ls ${{ github.workspace }}
     
      
